name: CI

on:
  push:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * 6'
jobs:
  build:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest, crystal: latest}
          - {os: ubuntu-latest, crystal: nightly}
          - {os: macos-latest}
          - {os: windows-latest, shards: false}
    runs-on: ${{matrix.os}}
    steps:
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{matrix.crystal}}
          shards: ${{matrix.shards}}
      - uses: actions/checkout@v2
      - run: crystal spec